// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelUpload():Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function DeleteDocument(arg1:number):Promise<void>;

export function GetCategories(arg1:main.TestConnectionRequest):Promise<Array<main.CategoryInfo>>;

export function GetConfig():Promise<main.Config>;

export function GetFileInfo(arg1:string):Promise<main.FileInfo>;

export function GetShareHistory():Promise<Array<main.ShareHistoryEntry>>;

export function HasStoredCredentials():Promise<boolean>;

export function OpenFileDialog():Promise<string>;

export function RevokeSharedLink(arg1:string):Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SetAuthCredentials(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ShareFiles(arg1:main.ShareRequest):Promise<main.ShareResponse>;
