// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelUpload() {
  return window['go']['main']['App']['CancelUpload']();
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DeleteDocument(arg1) {
  return window['go']['main']['App']['DeleteDocument'](arg1);
}

export function GetCategories(arg1) {
  return window['go']['main']['App']['GetCategories'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetShareHistory() {
  return window['go']['main']['App']['GetShareHistory']();
}

export function HasStoredCredentials() {
  return window['go']['main']['App']['HasStoredCredentials']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function RevokeSharedLink(arg1) {
  return window['go']['main']['App']['RevokeSharedLink'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetAuthCredentials(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetAuthCredentials'](arg1, arg2, arg3, arg4);
}

export function ShareFiles(arg1) {
  return window['go']['main']['App']['ShareFiles'](arg1);
}
